const Map<String, String> ar = {
  'Male': 'ذكر',
  'Female': 'انثى',
  'BMI Calculator': 'حاسبة مؤشر كتلة الجسم',
  'HEIGHT': 'طول القامة',
  'CM': 'سم',
  'Weight': 'وزن',
  'Age': 'سن',
  'Calculate': 'احسب',
  'Back to edit': 'الرجوع للتعديل',
  'Body mass index': 'مؤشر كتلة الجسم',
  'measure of body fat': 'قياس الدهون في الجسم',
  'Gender': 'جنس',
  'Result': 'نتيجة',
  'Re-Calculate': 'أعد الحساب',
  'Overweight': 'زيادة الوزن',
  'normal': 'طبيعى',
  'underweight': 'نقص الوزن',
  'Your have a': 'لديك',
  'in body weight.': 'فى وزن الجسم.',
  'BMI range :': 'نطاق مؤشر كتلة الجسم:',
  'Under 18,5': '18,5 تحت',
};