const Map<String, String> en = {
  'Male': 'Male',
  'Female': 'Female',
  'BMI Calculator': 'BMI Calculator',
  'HEIGHT': 'HEIGHT',
  'CM': 'CM',
  'Weight': 'Weight',
  'Age': 'Age',
  'Calculate': 'Calculate',
  'Back to edit': 'Back to edit',
  'Body mass index': 'Body mass index',
  'measure of body fat': 'measure of body fat',
  'Gender': 'Gender',
  'Result': 'Result',
  'Re-Calculate': 'Re-Calculate',
  'Overweight': 'Overweight',
  'normal': 'normal',
  'underweight': 'underweight',
  'Your have a': 'Your have a',
  'in body weight.': 'in body weight.',
  'BMI range :': 'BMI range :',
  'Under 18,5': 'Under 18,5',
};